/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/crm/factories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Factories */
        get: operations["get_factories_api_crm_factories_get"];
        put?: never;
        /**
         * Create Factory
         * @description Create a new factory
         */
        post: operations["create_factory_api_crm_factories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crm/factories/{factory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Factory By Id
         * @description Get a specific factory by factory_code
         */
        get: operations["get_factory_by_id_api_crm_factories__factory_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Factory
         * @description Update a factory's is_active and/or has_onsite status
         *     Only is_active and has_onsite fields can be modified
         */
        patch: operations["update_factory_api_crm_factories__factory_id__patch"];
        trace?: never;
    };
    "/api/crm/retailers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Retailers */
        get: operations["get_retailers_api_crm_retailers_get"];
        put?: never;
        /** Create Retailer */
        post: operations["create_retailer_api_crm_retailers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crm/retailers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Retailer By Id
         * @description Get a specific retailer by id
         */
        get: operations["get_retailer_by_id_api_crm_retailers__id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Retailer
         * @description Delete a retailer
         */
        delete: operations["delete_retailer_api_crm_retailers__id__delete"];
        options?: never;
        head?: never;
        /** Update Retailer */
        patch: operations["update_retailer_api_crm_retailers__id__patch"];
        trace?: never;
    };
    "/api/crm/blueprints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Blueprints
         * @description Get all blueprints with optional factory filter
         */
        get: operations["get_blueprints_api_crm_blueprints_get"];
        put?: never;
        /**
         * Create Blueprint
         * @description Create a new blueprint with file upload
         */
        post: operations["create_blueprint_api_crm_blueprints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crm/blueprints/{blueprint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Blueprint
         * @description Get a specific blueprint by ID
         */
        get: operations["get_blueprint_api_crm_blueprints__blueprint_id__get"];
        /**
         * Update Blueprint
         * @description Update an existing blueprint
         */
        put: operations["update_blueprint_api_crm_blueprints__blueprint_id__put"];
        post?: never;
        /**
         * Delete Blueprint
         * @description Delete a blueprint
         */
        delete: operations["delete_blueprint_api_crm_blueprints__blueprint_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/max-sales-date": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Max Sales Date
         * @description Get the maximum sales date from fact_sales
         */
        get: operations["get_max_sales_date_api_warehouse_max_sales_date_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/overall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Overall
         * @description Get overall warehouse data with sales and order statistics.
         *     Returns aggregated data by month with target comparisons.
         */
        get: operations["get_overall_api_warehouse_overall_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/factory-sales-range-diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Factory Sales Range Diff
         * @description Get sales by factories for 2 date range, whole month sales and scheduled delivery
         *     Return the diff of these 2 date range
         */
        get: operations["get_factory_sales_range_diff_api_warehouse_factory_sales_range_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/factory-order-range-diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Factory Order Range Diff
         * @description Get order by factories for 2 date range, whole month order and scheduled delivery
         *     Return the diff of these 2 date range
         */
        get: operations["get_factory_order_range_diff_api_warehouse_factory_order_range_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/product-sales-range-diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Factory Sales Range Diff
         * @description Get sales by product for 2 date range
         *     Return the diff of these 2 date range
         */
        get: operations["get_factory_sales_range_diff_api_warehouse_product_sales_range_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/product-order-range-diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Factory Order Range Diff
         * @description Get order by product for 2 date range
         *     Return the diff of these 2 date range
         */
        get: operations["get_factory_order_range_diff_api_warehouse_product_order_range_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/scheduled-and-actual-sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scheduled And Actual Sales
         * @description Compare scheduled deriveries and actual sales group by month
         */
        get: operations["get_scheduled_and_actual_sales_api_warehouse_scheduled_and_actual_sales_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/sales-overtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sales Pivot
         * @description Pivot table for sales data with dynamic grouping
         */
        get: operations["get_sales_pivot_api_warehouse_sales_overtime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/is-same-month": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sales Pivot */
        get: operations["get_sales_pivot_api_warehouse_is_same_month_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/sales-order-pct-diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sales Pivot */
        get: operations["get_sales_pivot_api_warehouse_sales_order_pct_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/thinner-paint-ratio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sales Pivot */
        get: operations["get_sales_pivot_api_warehouse_thinner_paint_ratio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/fact-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fact Order
         * @description All column from fact order
         */
        get: operations["get_fact_order_api_warehouse_fact_order_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/fact-sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fact Sales
         * @description All column from fact sales
         */
        get: operations["get_fact_sales_api_warehouse_fact_sales_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/etl/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Sales File
         * @description Upload and process sales Excel file for ETL
         *
         *     - **file**: Excel file (.xlsx or .xls) containing sales data
         *
         *     Returns processing results including rows inserted
         */
        post: operations["upload_sales_file_api_etl_sales_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/etl/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Order File
         * @description Upload and process order Excel file for ETL
         *
         *     - **file**: Excel file (.xlsx or .xls) containing order data
         *
         *     Returns processing results including rows inserted
         */
        post: operations["upload_order_file_api_etl_order_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sales Data */
        get: operations["get_sales_data_api_sales__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wh-overall/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wh Overall */
        get: operations["get_wh_overall_api_wh_overall__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Blueprint */
        Blueprint: {
            /**
             * Id
             * Format: uuid
             * @description Blueprint UUID
             */
            id: string;
            /**
             * Factory
             * @description Factory code
             */
            factory: string;
            /**
             * Name
             * @description Blueprint name
             */
            name: string;
            /** @description Production line type */
            type: components["schemas"]["ProductionLineType"];
            /**
             * Description
             * @description Blueprint description
             */
            description?: string | null;
            /**
             * File Path
             * @description File storage path
             */
            file_path: string;
            /**
             * File Url
             * @description Dynamic public url
             */
            file_url: string;
            /**
             * Filename
             * @description Original filename
             */
            filename: string;
            /**
             * File Size
             * @description File size in bytes
             */
            file_size: number;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        /** BlueprintUpdate */
        BlueprintUpdate: {
            /**
             * Name
             * @description Blueprint name
             */
            name?: string | null;
            /** @description Production line type */
            type?: components["schemas"]["ProductionLineType"] | null;
            /**
             * Description
             * @description Blueprint description
             */
            description?: string | null;
        };
        /** Body_create_blueprint_api_crm_blueprints_post */
        BlueprintCreate: {
            /** Factory */
            factory: string;
            /** Name */
            name: string;
            /** Type */
            type: components["schemas"]["ProductionLineType"];
            /** Description */
            description?: string | null;
            /**
             * File
             * Format: binary
             */
            file: File
        };
        /** Body_upload_order_file_api_etl_order_post */
        Body_upload_order_file_api_etl_order_post: {
            /**
             * File
             * Format: binary
             * @description Order Excel file to upload
             */
            file: string;
        };
        /** Body_upload_sales_file_api_etl_sales_post */
        Body_upload_sales_file_api_etl_sales_post: {
            /**
             * File
             * Format: binary
             * @description Sales Excel file to upload
             */
            file: string;
        };
        /** FactOrder */
        FactOrder: {
            /** Order Date */
            order_date?: string | null;
            /** Order Code */
            order_code?: string | null;
            /** Ct Date */
            ct_date?: string | null;
            /** Factory Code */
            factory_code?: string | null;
            /** Factory Order Code */
            factory_order_code?: string | null;
            /** Tax Type */
            tax_type?: string | null;
            /** Department */
            department?: string | null;
            /** Salesman */
            salesman?: string | null;
            /**
             * Deposit Rate
             * @default 0
             */
            deposit_rate: number | null;
            /** Payment Registration Code */
            payment_registration_code?: string | null;
            /** Payment Registration Name */
            payment_registration_name?: string | null;
            /** Delivery Address */
            delivery_address?: string | null;
            /** Product Code */
            product_code?: string | null;
            /** Product Name */
            product_name?: string | null;
            /** Qc */
            qc?: string | null;
            /** Warehouse Type */
            warehouse_type?: string | null;
            /**
             * Order Quantity
             * @default 0
             */
            order_quantity: number | null;
            /**
             * Delivered Quantity
             * @default 0
             */
            delivered_quantity: number | null;
            /**
             * Package Order Quantity
             * @default 0
             */
            package_order_quantity: number | null;
            /**
             * Delivered Package Order Quantity
             * @default 0
             */
            delivered_package_order_quantity: number | null;
            /** Unit */
            unit?: string | null;
            /** Package Unit */
            package_unit?: string | null;
            /** Estimated Delivery Date */
            estimated_delivery_date?: string | null;
            /** Original Estimated Delivery Date */
            original_estimated_delivery_date?: string | null;
            /** Pre Ct */
            pre_ct?: string | null;
            /** Finish Code */
            finish_code?: string | null;
            /** Import Timestamp */
            import_timestamp?: string | null;
            /** Import Wh Timestamp */
            import_wh_timestamp?: string | null;
            /** Factory Name */
            factory_name?: string | null;
        };
        /** FactSales */
        FactSales: {
            /** Product Code */
            product_code?: string | null;
            /** Product Name */
            product_name?: string | null;
            /** Qc */
            qc?: string | null;
            /** Factory Code */
            factory_code?: string | null;
            /** Sales Date */
            sales_date?: string | null;
            /** Sales Code */
            sales_code?: string | null;
            /** Order Code */
            order_code?: string | null;
            /**
             * Sales Quantity
             * @default 0
             */
            sales_quantity: number | null;
            /** Unit */
            unit?: string | null;
            /**
             * Package Sales Quantity
             * @default 0
             */
            package_sales_quantity: number | null;
            /** Package Unit */
            package_unit?: string | null;
            /** Department */
            department?: string | null;
            /** Salesman */
            salesman?: string | null;
            /** Warehouse Code */
            warehouse_code?: string | null;
            /** Warehouse Type */
            warehouse_type?: string | null;
            /** Import Code */
            import_code?: string | null;
            /** Factory Order Code */
            factory_order_code?: string | null;
            /** Import Timestamp */
            import_timestamp?: string | null;
            /** Import Wh Timestamp */
            import_wh_timestamp?: string | null;
            /** Factory Name */
            factory_name?: string | null;
        };
        /**
         * Factory
         * @description Factory item for list view - matches your SQL SELECT
         */
        Factory: {
            /**
             * Factory Code
             * @description Factory code
             */
            factory_code: string;
            /**
             * Factory Name
             * @description Factory name
             */
            factory_name: string;
            /**
             * Salesman
             * @description Sales Reps
             */
            salesman: string;
            /**
             * Is Active
             * @description Active status
             */
            is_active: boolean;
            /**
             * Has Onsite
             * @description Has onsite facilities
             */
            has_onsite: boolean;
        };
        /**
         * FactoryDetail
         * @description Detailed factory view - for single factory endpoint
         */
        FactoryDetail: {
            /**
             * Factory Code
             * @description Factory code
             */
            factory_code: string;
            /**
             * Factory Name
             * @description Factory name
             */
            factory_name: string;
            /**
             * Salesman
             * @description Sales Reps
             */
            salesman: string;
            /**
             * Is Active
             * @description Active status
             */
            is_active: boolean;
            /**
             * Has Onsite
             * @description Has onsite facilities
             */
            has_onsite: boolean;
        };
        /** FactoryOrderRangeDiff */
        FactoryOrderRangeDiff: {
            /** Factory Code */
            factory_code: string;
            /** Factory Name */
            factory_name: string;
            /** Salesman */
            salesman: string;
            /** Order Quantity */
            order_quantity: number;
            /** Order Quantity Target */
            order_quantity_target: number;
            /** Quantity Diff */
            quantity_diff: number;
            /** Quantity Diff Abs */
            quantity_diff_abs: number;
            /** Quantity Diff Pct */
            quantity_diff_pct: number;
            /** Whole Month Order Quantity */
            whole_month_order_quantity: number;
            /** Planned Deliveries */
            planned_deliveries: number;
        };
        /** FactorySalesRangeDiff */
        FactorySalesRangeDiff: {
            /** Factory Code */
            factory_code: string;
            /** Factory Name */
            factory_name: string;
            /** Salesman */
            salesman: string;
            /** Sales Quantity */
            sales_quantity: number;
            /** Sales Quantity Target */
            sales_quantity_target: number;
            /** Quantity Diff */
            quantity_diff: number;
            /** Quantity Diff Abs */
            quantity_diff_abs: number;
            /** Quantity Diff Pct */
            quantity_diff_pct: number;
            /** Whole Month Sales Quantity */
            whole_month_sales_quantity: number;
            /** Planned Deliveries */
            planned_deliveries: number;
        };
        /** FactoryUpdate */
        FactoryUpdate: {
            /**
             * Is Active
             * @description Active status
             */
            is_active?: boolean | null;
            /**
             * Has Onsite
             * @description Has onsite facilities
             */
            has_onsite?: boolean | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IsSameMonth */
        IsSameMonth: {
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Same Month Sales */
            same_month_sales: number;
            /** Diff Month Sales */
            diff_month_sales: number;
            /** Total Sales */
            total_sales: number;
            /** Total Order */
            total_order: number;
        };
        /** Overall */
        Overall: {
            /** Month */
            month: number;
            /**
             * Sales Quantity
             * @default 0
             */
            sales_quantity: number | null;
            /**
             * Exclude Factory Sales Quantity
             * @default 0
             */
            exclude_factory_sales_quantity: number | null;
            /**
             * Remain Sales Quantity
             * @default 0
             */
            remain_sales_quantity: number | null;
            /**
             * Order Quantity
             * @default 0
             */
            order_quantity: number | null;
            /**
             * Exclude Factory Order Quantity
             * @default 0
             */
            exclude_factory_order_quantity: number | null;
            /**
             * Remain Order Quantity
             * @default 0
             */
            remain_order_quantity: number | null;
            /**
             * Sales Target Value
             * @default 0
             */
            sales_target_value: number | null;
            /**
             * Order Target Value
             * @default 0
             */
            order_target_value: number | null;
            /**
             * Sales Target Pct
             * @default 0
             */
            sales_target_pct: number | null;
            /**
             * Order Target Pct
             * @default 0
             */
            order_target_pct: number | null;
        };
        /** PaginatedResponse[Factory] */
        PaginatedFactoryList: {
            /**
             * Count
             * @description Total number of items
             * @example 123
             */
            count: number;
            /**
             * Next
             * @example http://api.example.org/factories/?offset=50&limit=50
             */
            next?: string | null;
            /**
             * Previous
             * @example http://api.example.org/factories/?offset=0&limit=50
             */
            previous?: string | null;
            /**
             * Results
             * @description Array of items
             */
            results: components["schemas"]["Factory"][];
        };
        /** PaginatedResponse[Retailer] */
        PaginatedRetailerList: {
            /**
             * Count
             * @description Total number of items
             * @example 123
             */
            count: number;
            /**
             * Next
             * @example http://api.example.org/factories/?offset=50&limit=50
             */
            next?: string | null;
            /**
             * Previous
             * @example http://api.example.org/factories/?offset=0&limit=50
             */
            previous?: string | null;
            /**
             * Results
             * @description Array of items
             */
            results: components["schemas"]["Retailer"][];
        };
        /** PivotThinnerPaintRatio */
        PivotThinnerPaintRatio: {
            /** Thinner Data */
            thinner_data: {
                [key: string]: unknown;
            }[];
            /** Paint Data */
            paint_data: {
                [key: string]: unknown;
            }[];
            /** Ratio Data */
            ratio_data: {
                [key: string]: unknown;
            }[];
        };
        /** ProductOrderRangeDiff */
        ProductOrderRangeDiff: {
            /** Product Name */
            product_name: string;
            /** Order Quantity */
            order_quantity: number;
            /** Order Quantity Target */
            order_quantity_target: number;
            /** Quantity Diff */
            quantity_diff: number;
            /** Quantity Diff Abs */
            quantity_diff_abs: number;
        };
        /** ProductSalesRangeDiff */
        ProductSalesRangeDiff: {
            /** Product Name */
            product_name: string;
            /** Sales Quantity */
            sales_quantity: number;
            /** Sales Quantity Target */
            sales_quantity_target: number;
            /** Quantity Diff */
            quantity_diff: number;
            /** Quantity Diff Abs */
            quantity_diff_abs: number;
        };
        /**
         * ProductionLineType
         * @enum {string}
         */
        ProductionLineType: "PALLET" | "HANGING" | "ROLLER";
        /**
         * Retailer
         * @description Retailer item for list view
         */
        Retailer: {
            /**
             * Id
             * Format: uuid
             * @description Retailer UUID
             */
            id: string;
            /**
             * Name
             * @description Retailer name
             */
            name: string;
        };
        /**
         * RetailerCreate
         * @description Schema for creating a new retailer
         */
        RetailerCreate: {
            /**
             * Name
             * @description Retailer name
             */
            name: string;
        };
        /**
         * RetailerDetail
         * @description Detailed retailer view - for single retailer endpoint
         */
        RetailerDetail: {
            /**
             * Id
             * Format: uuid
             * @description Retailer UUID
             */
            id: string;
            /**
             * Name
             * @description Retailer name
             */
            name: string;
        };
        /**
         * RetailerUpdate
         * @description Schema for updating a retailer
         */
        RetailerUpdate: {
            /**
             * Name
             * @description Retailer name
             */
            name: string;
        };
        /** SalesOrderPctDiff */
        SalesOrderPctDiff: {
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Sales Quantity */
            sales_quantity: number;
            /** Sales Pct Diff */
            sales_pct_diff: number;
            /** Remain Sales Quantity */
            remain_sales_quantity: number;
            /** Remain Sales Pct Diff */
            remain_sales_pct_diff: number;
            /** Order Quantity */
            order_quantity: number;
            /** Order Pct Diff */
            order_pct_diff: number;
            /** Remain Order Quantity */
            remain_order_quantity: number;
            /** Remain Order Pct Diff */
            remain_order_pct_diff: number;
        };
        /** ScheduledAndActualSales */
        ScheduledAndActualSales: {
            /** Scheduled Month */
            scheduled_month: number;
            /** Scheduled Quantity */
            scheduled_quantity: number;
            /** Sales Quantity */
            sales_quantity: number;
            /** Sales Pct */
            sales_pct: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_factories_api_crm_factories_get: {
        parameters: {
            query?: {
                is_active?: boolean;
                has_onsite?: boolean;
                search?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_Factory_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_factory_api_crm_factories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Factory"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Factory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_factory_by_id_api_crm_factories__factory_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                factory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactoryDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_factory_api_crm_factories__factory_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                factory_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Factory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_retailers_api_crm_retailers_get: {
        parameters: {
            query?: {
                search?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_Retailer_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_retailer_api_crm_retailers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetailerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetailerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_retailer_by_id_api_crm_retailers__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetailerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_retailer_api_crm_retailers__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_retailer_api_crm_retailers__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetailerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetailerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blueprints_api_crm_blueprints_get: {
        parameters: {
            query?: {
                factory?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blueprint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_blueprint_api_crm_blueprints_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_blueprint_api_crm_blueprints_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blueprint"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blueprint_api_crm_blueprints__blueprint_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blueprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blueprint"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_blueprint_api_crm_blueprints__blueprint_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blueprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlueprintUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blueprint"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_blueprint_api_crm_blueprints__blueprint_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blueprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_max_sales_date_api_warehouse_max_sales_date_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    get_overall_api_warehouse_overall_get: {
        parameters: {
            query?: {
                /** @description Start day */
                day__gte?: number;
                /** @description End day */
                day__lte?: number;
                /** @description Start month */
                month__gte?: number;
                /** @description End month */
                month__lte?: number;
                /** @description Year */
                year?: number;
                /** @description Target month */
                target_month?: number;
                /** @description Target year */
                target_year?: number;
                /** @description Factory code to exclude */
                exclude_factory?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overall"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_factory_sales_range_diff_api_warehouse_factory_sales_range_diff_get: {
        parameters: {
            query?: {
                threshold?: number;
                increase?: boolean;
                date__gte?: string;
                date__lte?: string;
                date_target__gte?: string;
                date_target__lte?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactorySalesRangeDiff"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_factory_order_range_diff_api_warehouse_factory_order_range_diff_get: {
        parameters: {
            query?: {
                threshold?: number;
                increase?: boolean;
                date__gte?: string;
                date__lte?: string;
                date_target__gte?: string;
                date_target__lte?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactoryOrderRangeDiff"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_factory_sales_range_diff_api_warehouse_product_sales_range_diff_get: {
        parameters: {
            query?: {
                factory?: string | null;
                date__gte?: string;
                date__lte?: string;
                date_target__gte?: string;
                date_target__lte?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSalesRangeDiff"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_factory_order_range_diff_api_warehouse_product_order_range_diff_get: {
        parameters: {
            query?: {
                factory?: string | null;
                date__gte?: string;
                date__lte?: string;
                date_target__gte?: string;
                date_target__lte?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOrderRangeDiff"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scheduled_and_actual_sales_api_warehouse_scheduled_and_actual_sales_get: {
        parameters: {
            query?: {
                /** @description Year */
                year?: number;
                factory?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledAndActualSales"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sales_pivot_api_warehouse_sales_overtime_get: {
        parameters: {
            query?: {
                year?: string;
                /** @description Comma-separated group by fields (e.g., year,quarter) */
                group_by?: string;
                factory?: string | null;
                product?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sales_pivot_api_warehouse_is_same_month_get: {
        parameters: {
            query?: {
                date__gte?: string;
                date__lte?: string;
                date_target__gte?: string;
                date_target__lte?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IsSameMonth"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sales_pivot_api_warehouse_sales_order_pct_diff_get: {
        parameters: {
            query?: {
                /** @description Factory code to exclude */
                exclude_factory?: string;
                date__gte?: string;
                date__lte?: string;
                date_target__gte?: string;
                date_target__lte?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesOrderPctDiff"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sales_pivot_api_warehouse_thinner_paint_ratio_get: {
        parameters: {
            query?: {
                /** @description Year */
                year?: number;
                /** @description Comma-separated thinner product types */
                thinner?: string;
                /** @description Comma-separated paint product types */
                paint?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PivotThinnerPaintRatio"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fact_order_api_warehouse_fact_order_get: {
        parameters: {
            query?: {
                date__gte?: string;
                date__lte?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactOrder"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fact_sales_api_warehouse_fact_sales_get: {
        parameters: {
            query?: {
                date__gte?: string;
                date__lte?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactSales"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_sales_file_api_etl_sales_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_sales_file_api_etl_sales_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_order_file_api_etl_order_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_order_file_api_etl_order_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_sales_data_api_sales__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_wh_overall_api_wh_overall__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
